### ISSUE TITLE
Keyboard isn't able to be used with system dialogs

### ISSUE THREAD

**Issue by Vishram1123** [Vishram1123/gjs-osk#11]
See #7 for more info.

TLDR: Clicking on a system dialog (i.e. password dialog, folder name edit, etc..) will show the keyboard, but clicking on the keyboard will do nothing.

**Comment by Vishram1123** [comment]
Finally fixed this in the latest commit!!

**Comment by kdolum** [comment]
Thanks for working on this!  Unfortunately, it is not working correctly for me in autorelease fb1169f on my SP6 with Ubuntu 24.04, Gnome 46.  When the modal appears, both the GJS and the system OSK appear.  If I have them in different places, the GJS OSK works but the system OSK does not respond.  If I have them in the same place, the system OSK appears on top, and since it doesn't respond (not even to the dismiss button), I can't do anything except cancel the dialog.

**Comment by kdolum** [comment]
Unsurprisingly, my problem is fixed by turning off the the built-in screen keyboard in Settings -> Accessibility.  So as long as everything works and I never get stuck without any screen keyboard, I'm all set.  Thanks again.

**Comment by Vishram1123** [comment]
828ecdbb6d514a15347a5447d2f563bb4b69e9b7 turns off the built in osk when enabling gjs-osk @kdolum
