### ISSUE TITLE
Port to ESM

### ISSUE THREAD

**Issue by PhilDevProg** [Vishram1123/gjs-osk#15]
This is required for GNOME 45: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#prefs-js

**Comment by Vishram1123** [comment]
Will get on this once college applications settle down

**Comment by fjsevilla-dev** [comment]
Hi @Vishram1123 , first thanks for the extension, I use Gnome on my Steam Deck and it is the only OSK alternative to the one included in Gnome that meets my needs (work in Wayland, additional keys like Ctrl, Esc, Tab, etc and open on demand).

I have ported the extension to Gnome Shell 45, which includes porting the code to ECMAScript modules. I am using and testing it and it seems to work correctly:

https://github.com/fjsevilla-dev/gjs-osk/tree/gnome-shell-45

Note that gnome-shell >= 45.rc.1 is requiered, since I use [addExternalIndicator() ](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2894.)

If you find it helpful I have no problem to make a PR if you consider it appropriate. 

Note that the conversion to ESM implies breaking the backward compatibility of the code, so if you want to maintain support for pre-45 versions, you will need to maintain two separate versions of the extension and upload two separate versions to extensions.gnome.org.

**Comment by Vishram1123** [comment]
Hey @fjsevilla-dev, feel free to create a pr for your change. I will create a new branch for pre-45 releases (that I will update alongside 45+ releases stored in the main branch) eventually, once I get most of my school stuff sorted out. Thanks for the assistance!

**Comment by Vishram1123** [comment]
Thank you for the assistance @fjsevilla-dev! I have merged your PR into the main branch, and created a pre-45 branch. Sorry for my lack of activity as of late; I have had a lot of stuff going on.
