### ISSUE TITLE
Feature request - Option to reduce/remove margins

### ISSUE THREAD

**Issue by Pastitas** [Vishram1123/gjs-osk#39]
In the readme there's a section that lists not taking up the full width, but It's unclear to me if this is intended or a bug.
Is there any knowledge so far about those margins if it's a bug, and if it's a feature could it be tweaked?

**Comment by Vishram1123** [comment]
There was a pull request made a while back to change the spacing preferences. It is intended to have a border when you set the width to 100%; what I was talking about when it said that it wasn't taking up the full width was that you could snap to the left and right separately when setting the width to 100% (as in, it wasn't properly setting the width to the maximum size minus the spacing). I will add an option to change the snap spacing, but the bug I am referring to is unrelated to the spacing on the left and right; that is fully intentional

**Comment by Pastitas** [comment]
Okay then I kinda got it as it was. Thanks for considering this!

**Comment by Vishram1123** [comment]
Implemented in ad33bdd4e062974d85b571c3671bcc4e603b9cab. The issue with the keyboard not taking up the full width still exists, though I believe this is a rounding issue, as st.button doesn't like floating point values for width and height
