### ISSUE TITLE
Error when adding layout

### ISSUE THREAD

**Issue by oyvindknustad** [Vishram1123/gjs-osk#45]
Hi. Love this extension. I'm not sure this is a bug or something I'm doing wrong.

I'm trying to add a Norwegian layout by following the ReadMe. When I'm done and want to try it out, it gives the error:

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/ca243869-f7f0-4e08-ab77-4d5ae341c188)

Here's what I did:
I updated the keycodes.json, first with most of the new layout, then with only one letter changed to see if there was something I screwed up in there. I then added the name to langList in prefs.js and to keycodes in extension.js (which now are on lines 48 and 67. Some code must have been written since the line numbers are different from the ReadMe.)

I'm thinking that there's a flaw in the keycodes.json that makes the GLib.file_get_contents function not ok, and then the keycodes variable won't get assigned anything. But I can't figure out what I'm doing wrong in the json file.

**Comment by oyvindknustad** [comment]
Update: It might be a system thing. Because now I get that error and a grey square up in the left corner of the screen, the moment I reinstall the extension.

![image](https://github.com/Vishram1123/gjs-osk/assets/93269111/99b18c7d-a6a2-4b56-9071-4cc83116f8e9)

**Comment by Vishram1123** [comment]
Would you mind sending me your keycodes.json, so I can look through it to see if anything's wrong with it?

**Comment by Vishram1123** [comment]
I figured out what is happening. In order for this to work, you would need to recreate the entire Spanish layout in keycodes.json, and then on line 547 and 548, you would need to input the corresponding keyboard layout. Right now, because the added keyboard layout is not associated with a built in input source, it cannot initialize the keyboard with an input source. You could fix this by finding the associated keyboard layout, but I would simply suggest using the compose key combined with key sequences to accomplish the same effect. I will see if I have time to implement a Norwegian layout, but it appears that I am gonna have to implement a 4th layer (alt + shift) in order to accomplish this.

**Comment by Vishram1123** [comment]
@oyvindknustad @OscarParzon I added the rest of the 584 layouts that are a part of xkb (which probably includes the Norwegian layout), so updating to the latest should get you the same layout that you use on your keyboard regularly.
