### ISSUE TITLE
Request: add opacity/transparency, and maybe bold letters

### ISSUE THREAD

**Issue by Dr0gelix** [Vishram1123/gjs-osk#52]
Not sure if I am all alone with this kind of request, but sometimes the OSK is over a window where you can't see your input anymore (while used with 95% width, and 40% height). Adding opacity would kind of fix this issue for me.

I am not sure if it is possible to add the same function as on a mobile phone where it scrolls the text/window up when it is too close to the keyboard so you always see your input.

I am new to this extensions so keep it easy on me, since the demo videos does have different colours for each letter, that you can't change in the GJS OSK settings – so maybe I am failing to see the obvious. If there is a way please let me know.

**Comment by Vishram1123** [comment]
Sure, I will add the option to change transparency of the keyboard and make keys bold. It is going to be difficult to scroll up the window, because there is no API for interacting with applications in such a manner, so the closest thing I can do is to shrink the desktop to accommodate the keyboard, but even this would be difficult, as (unlike the built in OSK) this keyboard can be configured to open in any corner of the screen and be moved around. This would make it difficult to determine the desktop sizing, so as such, I won't be able to do this.

**Comment by Dr0gelix** [comment]
Thanks alot Vishram, but the opacity would help a lot in my use case and would be more than enough.

Is there anyway to alter the keyboard further? When I watched the demo videos, it seemed that the keys were differently coloured like a RGB keyboard etc?

**Comment by Vishram1123** [comment]
In the demo video, I just set the color of the background. The keys are colored based on the perceived darkness of the keyboard. If they are too bright, the keys are made a darker shade to stand out among the background. If the keys are too dark, the keys are made a lighter shade.

**Comment by Vishram1123** [comment]
Speaking of which, the mega-commit (sorry for the lack of organization) 1fad5fd adds transparency and bold character possibilities. Bold keys are changed with a toggle, and transparency is set by changing the transparency slider in the color picker for the background color
