### ISSUE TITLE
Feature Request: remember keyboard position after dragging and closing

### ISSUE THREAD

**Issue by guillerolle** [Vishram1123/gjs-osk#59]
It would be nice the keyboard remembered it's position on screen after being dragged. When you close it and reopen it, you must drag it again to a comfortable position. On my tablet, I find it more comfortable to type with kb at around middle of the screen but it always pops up from the bottom, which, combined with [#58](https://github.com/Vishram1123/gjs-osk/issues/58#issue-2431035653) makes the experience a bit fustrating
¿

**Comment by Vishram1123** [comment]
The reason I haven't implemented this yet is because sometimes the keyboard can be dragged off screen, and reopening it ensures that the keyboard returns to a predictable and reachable spot on the screen. For now, you can choose the default position in the settings as "Center":
![image](https://github.com/user-attachments/assets/8d80a6a0-a86c-4aca-8344-28bdcbebc395)

**Comment by guillerolle** [comment]
> The reason I haven't implemented this yet is because sometimes the keyboard can be dragged off screen, and reopening it ensures that the keyboard returns to a predictable and reachable spot on the screen. For now, you can choose the default position in the settings as "Center":
> ![image](https://github.com/user-attachments/assets/8d80a6a0-a86c-4aca-8344-28bdcbebc395)
> 

Ok, I understand! That would be quite a problem if the keyboard just left the screen hehe I thought I had cycled through all the settings a lot of times but definitely missed that one. That might help, thanks !
